# Generated by Django 6.0.1 on 2026-02-03 05:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Hamster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True)),
                ('exp', models.IntegerField(default=0)),
                ('hunger', models.IntegerField(default=100)),
                ('happiness', models.IntegerField(default=100)),
                ('cleanliness', models.IntegerField(default=100)),
                ('hamster_type', models.CharField(default='정글리안', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
