# Generated by Django 6.0.1 on 2026-02-03 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hamster', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hamster',
            name='level',
            field=models.IntegerField(default=1),
        ),
    ]
